### ISSUE TITLE
debugSpigot/Paper copies *-sources.jar instead of primary plugin

### ISSUE THREAD

**Issue by Silthus** [spigradle/spigradle#15]
Thanks for the fix in 1.3.1 with the inherited plugin class, it works now :)

However I found another bug that has to do with the `debugSpigot` and the other `debug*` tasks. When I configure gradle to compile my project with sources and javadocs, the sources jar gets copied into the plugins folder.

```gradle
java {
    withJavadocJar()
    withSourcesJar()
}
```

![image](https://user-images.githubusercontent.com/755327/86291536-5d975c80-bbef-11ea-88b2-fdb2baae25b7.png)

If I comment out the part with the sources  it works fine. If I only use the javadoc part it works fine as well.

**Comment by EntryPointKR** [comment]
Hi @Silthus, thanks for the report. it should be fixed now.
