### ISSUE TITLE
cannot find main class in multi-module situation.

### ISSUE THREAD

**Issue by portlek** [spigradle/spigradle#23]
Images say everything. spigradle can't find the main class although I wrote the main property to the spigot { here }.
![image](https://user-images.githubusercontent.com/12835420/87203110-9da2c180-c30a-11ea-9879-43920c2208f6.png)
![image](https://user-images.githubusercontent.com/12835420/87203127-a4c9cf80-c30a-11ea-8ac8-0eb396131804.png)
![image](https://user-images.githubusercontent.com/12835420/87203170-b57a4580-c30a-11ea-8377-b6a1b57eee46.png)
![image](https://user-images.githubusercontent.com/12835420/87203178-b9a66300-c30a-11ea-8679-0646f3497738.png)

**Comment by EntryPointKR** [comment]
Hi @portlek, that seems caused by unconfigured `spigot` in the root project. 
To avoid this, use buildscript instead of plugins DSL for apply Spigradle, and apply in the subprojects {} block:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'kr.entree:spigradle:2.0.1'
    }
}

subprojects {
    apply plugin: 'kr.entree.spigradle'
}
```
If still a matter, please provide the source code for reproducing.

**Comment by portlek** [comment]
I couldn't make it ;(
https://github.com/Infumia/BlockLimiter

**Comment by EntryPointKR** [comment]
Your project seems the `JavaPlugin` used in the `blocklimiter-plugin`, and used the shortcut `spigot()` in the `blocklimiter-nms`.
Therefore, the solution is:

1. Replace to the base plugin `kr.entree.spigradle.base` from [build.gradle#L2](https://github.com/Infumia/BlockLimiter/blob/master/build.gradle#L2) and [build.gradle#L9](https://github.com/Infumia/BlockLimiter/blob/master/build.gradle#L9)
2. Apply the spigot plugin `kr.entree.spigradle` in [blocklimiter-plugin/build.gradle](https://github.com/Infumia/BlockLimiter/blob/master/blocklimiter-plugin/build.gradle#L1). You can use plugins {} DSL in there.

**Comment by portlek** [comment]
![image](https://user-images.githubusercontent.com/12835420/87223406-5c032c80-c385-11ea-9733-3fe9521945da.png)
![image](https://user-images.githubusercontent.com/12835420/87223409-60c7e080-c385-11ea-9a4a-856d523d77ab.png)
i didnt but its not working
![image](https://user-images.githubusercontent.com/12835420/87223414-6cb3a280-c385-11ea-82ec-f0bf25ac5edb.png)

**Comment by portlek** [comment]
ok i did with  removing the version from blocklimiter-plugin.
