### ISSUE TITLE
Issues with `prepareSpigotPlugins`

### ISSUE THREAD

**Issue by NickAcPT** [spigradle/spigradle#26]
I'm having some issues when using `prepareSpigotPlugins` with a Gradle project with a subproject.

Here's the structure:
```
Root project 'ProjectA'
\--- Project ':ProjectB'
```

`ProjectB` is a dependency of `ProjectA`.

## First issue - Transitive Dependencies:

`ProjectB` depends on WorldEdit (`compileOnly(worldedit("7.2.0-SNAPSHOT"))`).

When invoking `prepareSpigotPlugins` on `:`(basically, ProjectA), it'll also execute for `ProjectB` because A depends on B. But, WorldEdit is only copied to `ProjectB\debug\spigot\plugins`.
It means I'll either have to also make `ProjectA` depend on WorldEdit (which it already does because it is a transitive dependency), or manually copy it into the correct folder.

## Second issue - `prepareSpigotPlugins` not copying properly

After building `ProjectA` and running `prepareSpigotPlugins`, one would expect `ProjectA\debug\spigot\plugins\ProjectB-1.0-SNAPSHOT.jar` to show up with the last changes like `ProjectA\debug\spigot\plugins\ProjectA-1.0-SNAPSHOT.jar` does.

I found that if I remove some files from the `ProjectB` jar file that is on the plugins folder, the task will copy it, but not after a normal build (without cleaning since I don't need to do it).

**Comment by EntryPointKR** [comment]
Hi @NickAcPT, Thank you for the report :)
I'm currently working on another project, the issues will be fixed when I have finished.

**Comment by EntryPointKR** [comment]
Thanks @NickAcPT, Should be fixed now. If still have a issue, please post the `build.gradle` for reproduce.
