### ISSUE TITLE
debugPaper not working with shadowJar

### ISSUE THREAD

**Issue by Magnum97** [spigradle/spigradle#27]
I have authored plugins that use [shadow](https://github.com/johnrengelman/shadow) to compile dependencies. When run alone the shadowJar task functions fine and I get the uber jar as expected. I have added `tasks.debugPaper.dependsOn shadowJar` and the tasks run fine but in the spigot/paper plugins folder I only get the lean jar. I have the shadowJar task overwrite the lean jar with the uber jar, but that does not fix this problem.

**Comment by EntryPointKR** [comment]
Hi @Magnum97, the jar copy task is [prepareSpigotPlugins](https://github.com/spigradle/spigradle/blob/master/docs/spigot_plugin.md#preparespigotplugins---copy), so you must make `shadowJar` depends on the `prepareSpigotPlugins` at least, the best is on [assemble](https://docs.gradle.org/current/userguide/base_plugin.html#sec:base_tasks) or jar.
You can try: `jar.dependsOn(shadowJar)`, this should be work.

I'll add some shadowJar tips on docs, Thank you for sharing your experience

**Comment by Magnum97** [comment]
`tasks.prepareSpigotPlugins.dependsOn shadowJar` does exactly what I wanted - thanks for the help!
