### ISSUE TITLE
Unable to use `Spigradle` and `Spigradle Bungee` on the same project.

### ISSUE THREAD

**Issue by NickAcPT** [spigradle/spigradle#31]
Intellij gives this Warning:

<i><b>root project '\<project name>': Unable to build IntelliJ project settings</b>
Details: java.lang.IllegalStateException: Could not create domain object 'prepareServer' (GradleTask)
Caused by: org.gradle.api.UnknownTaskException: Task with name 'prepareBungee' not found in root project '\<project name>'.</i>

Reproduction repo: https://github.com/NickAcPT/LoversSync/tree/2cee56990c2d3a903a426a234565838ba84545b1

Depending how the project is setup, it will also make it so the Spigradle Bungee plugin picks the wrong Main class.
Output:
```yaml
main: io.github.nickac.loverssync.spigot.LoversSyncSpigot
```
Expected:
```yaml
main: io.github.nickac.loverssync.bungee.LoversSyncBungee
```

**Comment by NickAcPT** [comment]
@EntryPointKR It appears that the error message above from Intellij appears even when not using both plugins.

**Comment by EntryPointKR** [comment]
Thank you for the report and providing the reproduction repo @NickAcPT, this should be fixed now.
