### ISSUE TITLE
debugSpigot/debugPaper task always uses Minecraft 1.15.2

### ISSUE THREAD

**Issue by Silthus** [spigradle/spigradle#37]
The `debug*` tasks do not use the version defined as mcVersion in the build.gradle dependencies. But they should use the version we define to download and build the test server.

**Comment by AidanWright** [comment]
The debug tasks use the build version set in `build.gradle`. If this is not set, it defaults to 1.15.2. For example, if you want the sever to run 1.16.4, change the `build.gradle` to include,
```
spigot {
   debug {
        buildVersion = "1.16.4"
   }
}
```
Or, if you want it to use the mcVersion, change it to
```
spigot {
   debug {
        buildVersion = project.property("mcVersion")
   }
}
```

**Comment by Silthus** [comment]
Ah ok, thank you!

Aidan <notifications@github.com> schrieb am So. 22. Nov. 2020 um 00:14:

**Comment by EntryPointKR** [comment]
Sorry for the lack of documentation, this will be documented ASAP also with javadocs.
Would be good if we can inference the buildVersion from the `spigot()` in dependencies.
