### ISSUE TITLE
Extend Spigradle support to Spigot and Paper 1.16.x

### ISSUE THREAD

**Issue by Ungolim** [spigradle/spigradle#39]
Excellent plugin @EntryPointKR, I was wondering whether you guys are considering extending Spigradle support for the latest Minecraft server version (1.16.4) for at least Spigot and Paper along with their respective APIs

https://github.com/lepidotteri/ARM-Minecraft/blob/fb016fb688be41cfa6fa98c8bca730d0351fa774/build.gradle#L28

**Comment by EntryPointKR** [comment]
@lepidotteri Thank you for reminding me bumping up the default version, it will be updated with upcoming Gradle 6.8.
Before the update, still you can use 1.16.4 to set the `buildVersion` manually.
Here is @AidanWright's clear example: https://github.com/spigradle/spigradle/issues/37#issuecomment-731650810.
