### ISSUE TITLE
softdepend missing

### ISSUE THREAD

**Issue by Peda1996** [spigradle/spigradle#41]
It is not possible to define a softdepend in the spigot {} section. Is there a way to add this?

**Comment by EntryPointKR** [comment]
@Peda1996 You can use [`softDepends`](https://github.com/spigradle/spigradle/blob/master/src/main/kotlin/kr/entree/spigradle/module/spigot/SpigotExtension.kt#L175) in the spigot {}.

Kotlin example:
```kotlin
spigot {
    softDepends = listOf("MyDependency")
}
```

Groovy example:
```groovy
spigot {
    softDepends 'MyDependency'
}
```

This example will be added in the spigradle-sample project.

**Comment by Peda1996** [comment]
Thanks 👍 

I didn't know that I had to write Camelcase.

**Comment by Silthus** [comment]
I had the same problem, thanks for the docs.
