### ISSUE TITLE
Downloading plugins on debug task run

### ISSUE THREAD

**Issue by CDFN** [spigradle/spigradle#42]
Hey, is it possible to disable downloading dependency plugins by Spigradle? It keeps downloading wrong versions of worldedit and worldguard (I guess it downloads not shaded ones). On the picture below selected JARs are downloaded from dev.bukkit.org (official download source for WE and WG). You can see they have different sizes.
![image](https://user-images.githubusercontent.com/41289688/106333750-9a145f00-6289-11eb-82dc-960f85f91e6f.png)

**Comment by EntryPointKR** [comment]
Hi @CDFN, as [`preparePlugins`](https://github.com/spigradle/spigradle/blob/master/src/main/kotlin/kr/entree/spigradle/module/common/DebugTask.kt#L125) task is [`CopyTask`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Copy.html), yes you can ignore a specific dependency.

Groovy:
```groovy
prepareSpigotPlugins {
    exclude '**/worldedit*.jar' // or exclude 'worldedit*.jar'?
    exclude '**/worldguard*.jar'
}
```

Kotlin:
```kotlin
tasks {
    prepareSpigotPlugins {
        exclude("**/worldedit*.jar")
        exclude("**/worldguard*.jar")
    }
}
```

If you have other questions, feel free to ask here!

**Comment by CDFN** [comment]
Thank you very much for quick answer, it works excellent :) I'm not closing the issue in case you want to mention about it somewhere. If you want to close it, feel free to do so. I have no more questions :D
