### ISSUE TITLE
cant executor commands

### ISSUE THREAD

**Issue by squirtlecc** [spigradle/spigradle#43]
when i using `id("kr.entree.spigradle") version "2.2.3"` in my build.kts to depend spigot 1.16.5 ,i cant execute commands in my plugin, when i delete spigradle plugin in build.kts and using `compileOnly("org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT")`
the command enable.

**Comment by EntryPointKR** [comment]
Hi @squirtlecc , I'm sorry for the late response! I couldn't encounter the issue. Could you check your plugin was enabled without error or publish a repository to let me reproduce?
Feel free to ask me if you have anything I can help or close this issue. Thanks!

**Comment by networkException** [comment]
Maybe this is related, when I reload gradle seems to be unable to resolve spigot for 1.16.5 at all. 1.16.4 works fine though
![image](https://user-images.githubusercontent.com/42888162/114308955-cd733580-9ae5-11eb-9226-f6a52b9184ff.png)

**Comment by EntryPointKR** [comment]
Hi @networkException, Thanks for the logs, but I'm ok with 1.16.5. Please upload a repository for letting me reproduce and see what happens with just use `compileOnly 'org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT'`.

**Comment by networkException** [comment]
Now I can't seem to be able to reproduce this anymore, I'm guessing it was just a problem in the repo then

**Comment by fatevase** [comment]
> Hi @squirtlecc , I'm sorry for the late response! I couldn't encounter the issue. Could you check your plugin was enabled without error or publish a repository to let me reproduce?
> Feel free to ask me if you have anything I can help or close this issue. Thanks!

sorry for long time to reply you! It's all my fault, when i used this plugin i dont notice all configurations, i'm so sorry my question bothered you.

**Comment by squirtlecc** [comment]
> Hi @squirtlecc , I'm sorry for the late response! I couldn't encounter the issue. Could you check your plugin was enabled without error or publish a repository to let me reproduce?
> Feel free to ask me if you have anything I can help or close this issue. Thanks!

sorry for long time to reply you! It's all my fault, when i used this plugin i dont notice all configurations, i'm so sorry my question bothered you.

**Comment by EntryPointKR** [comment]
No problems @squirtlecc, if you had any problems, just opening it up!
