### ISSUE TITLE
[Feature] Support Java 16

### ISSUE THREAD

**Issue by aroooo** [spigradle/spigradle#51]
Hi, I tried using Spigradle on my project today and I encountered this error:
`Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '16'`

Edit: I also got this error:

`Execution failed for task ':detectSpigotMain'.
Unsupported class file major version 60`

Does this mean Java 16 is not supported yet? If so guess I'll wait for it to be supported.
Thank you.

**Comment by EntryPointKR** [comment]
Sorry for the delay! Until the update, we can just specify the main to avoid the error:
```
spigot {
    main = "package.Main"
}
```

Also note that the annotation way can be deprecated due the build-in way will be significantly improved!
