### ISSUE TITLE
[Enhancement] Import NMS from BuildTools

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [spigradle/spigradle#58]
I'm not fluent in Gradle, so I wouldn't be confident in making a pull request for this, however, seeing that Spigradle can use BuildTools to compile the server jar, would it be possible to use a similar feature to allow the importing of NMS into the dependencies. I'm thinking something along the lines of:
```
dependencies {
    compileOnly spigotNMS(<version>)
}
```

Which would run BuildTools, then use `mavenLocal()` to import the full jar. Would this be possible?
Thanks,
&nbsp;&nbsp;&nbsp;~BlockyPenguin

**Comment by EntryPointKR** [comment]
Feel free to open a issue if you have a problem! Any question is welcome.

**Comment by ThatBlockyPenguin** [comment]
Ah, thanks, didn't know this existed.
