### ISSUE TITLE
Support public library resolution in spigot >= 1.17

### ISSUE THREAD

**Issue by entrypointkr** [spigradle/spigradle#59]
`libraries` option in `plugin.yml`
https://www.spigotmc.org/threads/spigot-bungeecord-1-17.510208/#post-4184317

**Comment by EntryPointKR** [comment]
There are two ideas:

1. Create a new configuration for define a library that will be written in the `libraries`, and manually specify dependencies with it.
```groovy
// New configurations: libImplementation, libApi
dependencies {
    // This not be written in `plugin.yml`.
    compileOnly(spigot('1.16.2'))
    // This will be. implementation + lib
    libImplementation("org.jetbrains.kotlin:kotlin-stdlib:1.5.10")
    // This either. api + lib
    libApi("org.sample:my-public-library:1.0.0") // 
}
```

2. Keep `compileOnly`, `implementation`, `api` semantics.
```groovy
dependencies {
    // This not be written in `plugin.yml`.
    compileOnly(spigot('1.16.2'))
    // This will be.
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.5.10")
    // This either.
    api("org.sample:my-public-library:1.0.0")
}
```

**Comment by entrypointkr** [comment]
> There are two ideas:
> 
>     1. Create a new configuration for define a library that will be written in the `libraries`, and manually specify dependencies with it.
> 
> 
> ```groovy
> // New configurations: libImplementation, libApi
> dependencies {
>     // This not be written in `plugin.yml`.
>     compileOnly(spigot('1.16.2'))
>     // This will be. implementation + lib
>     libImplementation("org.jetbrains.kotlin:kotlin-stdlib:1.5.10")
>     // This either. api + lib
>     libApi("org.sample:my-public-library:1.0.0") // 
> }
> ```
> 
>     2. Keep `compileOnly`, `implementation`, `api` semantics.
> 
> 
> ```groovy
> dependencies {
>     // This not be written in `plugin.yml`.
>     compileOnly(spigot('1.16.2'))
>     // This will be.
>     implementation("org.jetbrains.kotlin:kotlin-stdlib:1.5.10")
>     // This either.
>     api("org.sample:my-public-library:1.0.0")
> }
> ```

Decided the latter one.
