### ISSUE TITLE
Add support for Mojang mappings in 1.17+

### ISSUE THREAD

**Issue by embeddedt** [spigradle/spigradle#62]
As of 1.17, [Spigot now offers the ability to use the Mojang obfuscation mappings](https://www.spigotmc.org/threads/spigot-bungeecord-1-17.510208/#post-4184317) ("Mojmap") when developing plugins. However, it is necessary to remap the plugin JAR back to obfuscated names before running it on a server.

md_5 provides instructions on how to set this up in the linked post, but the instructions are for Maven. Is it possible that this functionality could be added to Spigradle directly?

**Comment by EntryPointKR** [comment]
That is really good idea, yes I will provide that feature. Thank you for the great idea @embeddedt!

**Comment by entrypointkr** [comment]
This implemented by a independent plugin, [gradle-specialsource](https://github.com/typecraft-io/gradle-specialsource)!
