### ISSUE TITLE
Java 16 not really working?

### ISSUE THREAD

**Issue by Emilius123** [spigradle/spigradle#68]
Hi,

Sorry for the uninforming title, my problem is so:

I would like to compile my plugin using JDK 16 and Java 16 stuff. When doing so though, gradle shouts at me:
`warning: Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '16'
1 warning`

Only workaround is setting the entire thing to Java 8:
`sourceCompatibility = 8
targetCompatibility = 8`

Apparently, detectSpigotMain needs everything to be >= Java 8. Actually, detectSpigotMain isn't even needed, though, since I'm already setting the main class in the spigot {} config in my build.gradle. 

What can I do here to avoid detectSpigotMain and fully use Java 16? Thanks in advance

**Comment by entrypointkr** [comment]
@Emilius123 Even the build warnings, I can build successfully in below environments:
1. Gradle `7.2`, Gradle JVM `openjdk-16`, Spigradle `2.2.4`
2. Gradle `6.9.1`, Gradle JVM `openjdk-8`, Spigradle `2.2.4`, [Toolchain for target 16](https://docs.gradle.org/current/userguide/toolchains.html#sec:consuming)

Please note that using Gradle 6 or lower doesn't compatible with jdk16+.
If you still have this problem, please upload a whole project to help me to reproduce!
