### ISSUE TITLE
i got this serror

### ISSUE THREAD

**Issue by WhiteClueGaming1** [spigradle/spigradle#74]

**Comment by WhiteClueGaming1** [comment]
C:\Users\AyushSaini\Desktop\New folder>java -Xmx1024M -Xms1024M -jar paperclip-1618.jar nogui
Exception in thread "main" io.papermc.fourohfour.FourOhFour:

############################################################################################
#                                                                                          #
#                                        Hey there!                                        #
#                                                                                          #
#------------------------------------------------------------------------------------------#
#                                                                                          #
#   The endpoint you downloaded this application from is no longer in service. In order    #
#     to continue using this application, please view our API documentation for details    #
#     on how to access downloads: https://papermc.io/api/docs/                             #
#                                                                                          #
############################################################################################



C:\Users\AyushSaini\Desktop\New folder>PAUSE
Press any key to continue . . .

**Comment by WhiteClueGaming1** [comment]
pls help

**Comment by entrypointkr** [comment]
Hi @WhiteClueGaming1, this is fixed from 2.3.x, can you check Spigradle version is latest and remove the `server.jar` in debug folder and retry?

**Comment by entrypointkr** [comment]
closing as no response was provided
