### ISSUE TITLE
BStats implementation.

### ISSUE THREAD

**Issue by rickmartensnl** [spigradle/spigradle#75]
I'm trying to implement BStats with Spigradle.
I knew I had to shade BStats in my plugin with relocating the packages. When I was searching for how I could do this, I found a dependency(`com.github.johnrengelman.shadow:6.1.0`) that was working, however it broke the `prepareSpigotPlugins` task.
I am using Gradle Kotlin. Does anyone know how to add BStats with relocating the packages, or how to fix that `prepareSpigotPlugins` copies the jar generated by shadow, instead of doing nothing?

**Comment by entrypointkr** [comment]
You can use the prepare task if you do `assemble.dependsOn(shadowJar)`

**Comment by rickmartensnl** [comment]
Do you have a full example? Because it is adding the Kotlin package, but not adding a relocated BStats or the normal BStats.

**Comment by entrypointkr** [comment]
Feel free to open a issue if you have another question!
