### ISSUE TITLE
create a new configuration `spigotImplementation` for the `libraries` plugin option

### ISSUE THREAD

**Issue by entrypointkr** [spigradle/spigradle#76]

**Comment by Cloudate9** [comment]
I second this. A way to disable library would be nice, especially when we want to shade libraries instead of downloading at runtime

**Comment by entrypointkr** [comment]
Workaround for shadowJar
```java
dependencies {
    shadow project(':my-shadow-project')
   // shadow 'my.shadow:project:1.0.0'
}

shadowJar {
    configurations = [project.configurations.runtimeClasspath, project.configurations.shadow]
}
```

**Comment by entrypointkr** [comment]
Will be fixed with `SpigotExtension#excludeLibraries` in Spigradle 2.4
To exclude `com.squareup.okhttp3:okhttp:4.9.0` library, just put `okhttp`:
```groovy
spigot {
    excludeLibraries = ['okhttp'] 
    // or fullname 'com.squareup.okhttp3:okhttp:4.9.0'
}
```
```kotlin
spigot {
    excludeLibraries = listOf("okhttp")
}
```
Current major 2.x, the libraries being added implicitly,
But next major, I'll consider explicit declaration like `spigotImplementation`.

**Comment by Cloudate9** [comment]
Would using regex such as * work to exclude all?

**Comment by entrypointkr** [comment]
@Cloudate9 Wildcard `*` support from 2.4.1 now, not as regex because too complex just for dependency notation, escaping dot makes ugly.
